### ISSUE TITLE
Traefik ready Docker Compose with healthcheck

### ISSUE THREAD

**Issue by vabene1111** [FacilMap/facilmap#237]
hi everyone, i just had some problems setting this up despite the great documentation so after getting it working I tought i would share my config.

This features
- Traefik support (can easily be removed by removing the labes and networks)
- mysql with health check (to prevent facilmap from starting before mysql starts which leads to crashes)
- mysql volume configuration (as a bind mount but could easily be changed to a volume)

```yml

version: "2.1"
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: facilmap
      MYSQL_USER: facilmap
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./mysqldata:/var/lib/mysql

  facilmap:
    image: facilmap/facilmap
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      USER_AGENT: My FacilMap (https://facilmap.example.org/, facilmap@example.org)
      DB_TYPE: mysql
      DB_HOST: db
      DB_NAME: facilmap
      DB_USER: facilmap
      DB_PASSWORD: password
      ORS_TOKEN: # Get an API key on https://go.openrouteservice.org/ (needed for routing)
      MAPBOX_TOKEN: # Get an API key on https://www.mapbox.com/signup/ (needed for routing)
      MAPZEN_TOKEN: # Get an API key on https://mapzen.com/developers/sign_up (needed for elevation info)
      MAXMIND_USER_ID: # Sign up here https://www.maxmind.com/en/geolite2/signup (needed for geoip lookup to show initial map state)
      MAXMIND_LICENSE_KEY:
    restart: unless-stopped
    labels: # traefik example labels
      - "traefik.enable=true"
      - "traefik.http.routers.maps.rule=Host(`url.example.com`)"
      - "traefik.http.routers.maps.entrypoints=entrypoint"
      - "traefik.http.routers.maps.tls.certresolver=certresolver"
    networks:
      - default
      - traefik


networks:
  default:
  traefik: # This is your external traefik network
    external: true

```
